# Generated by Django 3.2 on 2022-05-08 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220505_1303'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
